### ISSUE TITLE
9 Errors after update

### ISSUE THREAD

**Issue by MetalHeadSeven** [Hyphie24/MSBT-TWW#2]
1x MikScrollingBattleText/MikSBT.lua:29: attempt to call global 'GetAddOnMetadata' (a nil value)
[string "@MikScrollingBattleText/MikSBT.lua"]:29: in main chunk

Locals:
mod = <table> {
}
modName = "MikSBT"
GetSpellInfo = nil
(*temporary) = nil
(*temporary) = "MikScrollingBattleText"
(*temporary) = "Version"
(*temporary) = "attempt to call global 'GetAddOnMetadata' (a nil value)"

1x ...MikScrollingBattleText/Localization/localization.lua:28: attempt to index local 'L' (a nil value)
[string "@MikScrollingBattleText/Localization/localization.lua"]:28: in main chunk

Locals:
L = nil
(*temporary) = <table> {
 MSBT Heroic = "Interface\Addons\MikScrollingBattleText\Fonts\heroic.ttf"
 MSBT Transformers = "Interface\Addons\MikScrollingBattleText\Fonts\transformers.ttf"
 MSBT Bazooka = "Interface\Addons\MikScrollingBattleText\Fonts\bazooka.ttf"
 MSBT Cooline = "Interface\Addons\MikScrollingBattleText\Fonts\cooline.ttf"
 MSBT Diogenes = "Interface\Addons\MikScrollingBattleText\Fonts\diogenes.ttf"
 MSBT Yellowjacket = "Interface\Addons\MikScrollingBattleText\Fonts\yellowjacket.ttf"
 MSBT Porky = "Interface\Addons\MikScrollingBattleText\Fonts\porky.ttf"
 MSBT Ginko = "Interface\Addons\MikScrollingBattleText\Fonts\ginko.ttf"
 MSBT Adventure = "Interface\Addons\MikScrollingBattleText\Fonts\adventure.ttf"
 MSBT Talisman = "Interface\Addons\MikScrollingBattleText\Fonts\talisman.ttf"
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'L' (a nil value)"

1x ...rfaceMikScrollingBattleText/MSBTProfiles.lua:70: attempt to call local 'GetSkillName' (a nil value)
[string "@MikScrollingBattleText/MSBTProfiles.lua"]:70: in main chunk

Locals:
module = <table> {
}
moduleName = "Profiles"
L = nil
CopyTable = nil
EraseTable = nil
SplitString = nil
Print = nil
GetSkillName = nil
IsClassic = false
DEFAULT_PROFILE_NAME = "Default"
SAVED_VARS_NAME = "MSBTProfiles_SavedVars"
SAVED_VARS_PER_CHAR_NAME = "MSBTProfiles_SavedVarsPerChar"
SAVED_MEDIA_NAME = "MSBT_SavedMedia"
PET_SPACE = "Pet "
FLAG_YOU = 4026531840
TARGET_TARGET = 65536
REACTION_HOSTILE = 64
SPELLID_ELUSIVE_BREW = 126453
SPELLID_EXECUTE = 5308
SPELLID_FIRST_AID = 3273
SPELLID_HAMMER_OF_WRATH = 24275
SPELLID_LAVA_SURGE = 77762
SPELLID_REVENGE = 6572
SPELLID_VICTORY_RUSH = 34428
(*temporary) = nil
(*temporary) = 16870
(*temporary) = "attempt to call local 'GetSkillName' (a nil value)"

1x MikScrollingBattleText/MSBTParser.lua:30: attempt to call global 'GetSpellInfo' (a nil value)
[string "@MikScrollingBattleText/MSBTParser.lua"]:30: in main chunk

Locals:
module = <table> {
}
moduleName = "Parser"
Print = nil
EraseTable = nil
(*temporary) = nil
(*temporary) = 49020
(*temporary) = "attempt to call global 'GetSpellInfo' (a nil value)"

1x MikScrollingBattleText/MSBTMedia.lua:37: attempt to index local 'L' (a nil value)
[string "@MikScrollingBattleText/MSBTMedia.lua"]:37: in main chunk

Locals:
module = <table> {
}
moduleName = "Media"
MSBTProfiles = <table> {
}
L = nil
DEFAULT_SOUND_FILES = <table> {
 MSBT Low Mana = "Interface\Addons\MikScrollingBattleText\Sounds\LowMana.ogg"
 MSBT Cooldown = "Interface\Addons\MikScrollingBattleText\Sounds\Cooldown.ogg"
 MSBT Low Health = "Interface\Addons\MikScrollingBattleText\Sounds\LowHealth.ogg"
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'L' (a nil value)"

1x ...aceMikScrollingBattleText/MSBTAnimations.lua:53: attempt to index local 'L' (a nil value)
[string "@MikScrollingBattleText/MSBTAnimations.lua"]:53: in main chunk

Locals:
module = <table> {
}
moduleName = "Animations"
MSBTMedia = <table> {
}
MSBTProfiles = <table> {
}
L = nil
IsModDisabled = nil
EraseTable = nil
fonts = nil
sounds = nil
MAX_ANIMATIONS_PER_AREA = 15
DEFAULT_SCROLL_TIME = 3
DEFAULT_FADE_PERCENT = 0.800000
ANIMATION_DELAY = 0.015000
TEXT_ALIGN_MAP = <table> {
 1 = "BOTTOMLEFT"
 2 = "BOTTOM"
 3 = "BOTTOMRIGHT"
}
OUTLINE_MAP = <table> {
 1 = ""
 2 = "OUTLINE"
 3 = "THICKOUTLINE"
 4 = "MONOCHROME"
 5 = "MONOCHROME,OUTLINE"
 6 = "MONOCHROME,THICKOUTLINE"
}
DEFAULT_FONT_SIZE = 18
(*temporary) = "OUTLINE"
(*temporary) = "THICKOUTLINE"
(*temporary) = "MONOCHROME"
(*temporary) = "MONOCHROME,OUTLINE"
(*temporary) = "MONOCHROME,THICKOUTLINE"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'L' (a nil value)"

1x MikScrollingBattleText/MSBTLoot.lua:192: attempt to call field 'RegisterHandler' (a nil value)
[string "@MikScrollingBattleText/MSBTLoot.lua"]:192: in main chunk

Locals:
module = <table> {
}
moduleName = "Loot"
MSBTProfiles = <table> {
}
MSBTParser = <table> {
}
DisplayEvent = nil
GOLD = "Gold"
SILVER = "Silver"
COPPER = "Copper"
ITEM_TYPE_QUEST = "Quest"
_ = nil
qualityPatterns = <table> {
 1 = "|cFFffffff[%s]|r"
 2 = "|cFF1fff00[%s]|r"
 3 = "|cFF0071de[%s]|r"
 4 = "|cFFa436ef[%s]|r"
 5 = "|cFFff8100[%s]|r"
 6 = "|cFFe7cd81[%s]|r"
 7 = "|cFF00cdff[%s]|r"
 8 = "|cFF00cdff[%s]|r"
 0 = "|cFF9e9e9e[%s]|r"
}
(*temporary) = nil
(*temporary) = "attempt to call field 'RegisterHandler' (a nil value)"

1x MikScrollingBattleText/MSBTMain.lua:107: attempt to call local 'GetSkillName' (a nil value)
[string "@MikScrollingBattleText/MSBTMain.lua"]:107: in main chunk

Locals:
module = <table> {
}
moduleName = "Main"
MSBTAnimations = <table> {
}
MSBTMedia = <table> {
}
MSBTParser = <table> {
}
MSBTTriggers = <table> {
 powerTypes = <table> {
 }
 triggerSuppressions = <table> {
 }
 categorizedTriggers = <table> {
 }
}
MSBTProfiles = <table> {
}
L = nil
GetSpellInfo = nil
EraseTable = nil
GetSkillName = nil
ShortenNumber = nil
DisplayEvent = nil
IsScrollAreaActive = nil
IsScrollAreaIconShown = nil
TestFlagsAll = nil
triggerSuppressions = <table> {
}
powerTypes = <table> {
 HOLY_POWER = 9
 COMBO_POINTS = 4
 INSANITY = 13
 ALTERNATE_POWER = 10
 RUNES = 5
 ENERGY = 3
 MANA = 0
 CHI = 12
 MAELSTROM = 11
 ARCANE_CHARGES = 16
 PAIN = 18
 LUNAR_POWER = 8
 SOUL_SHARDS = 7
 FURY = 17
 ESSENCE = 19
 FOCUS = 2
 RUNIC_POWER = 6
 RAGE = 1
}
classMap = nil
MERGE_DELAY_TIME = 0.300000
THROTTLE_UPDATE_TIME = 0.500000
EMOTE_HOLD_TIME = 1
ENEMY_BUFF_HOLD_TIME = 5
DAMAGETYPE_PHYSICAL = 1
DAMAGETYPE_HOLY = 2
DAMAGETYPE_FIRE = 4
DAMAGETYPE_NATURE = 8
DAMAGETYPE_FROST = 16
DAMAGETYPE_SHADOW = 32
DAMAGETYPE_ARCANE = 64
DAMAGETYPE_HOLYSTRIKE = 3
DAMAGETYPE_FLAMESTRIKE = 5
DAMAGETYPE_STORMSTRIKE = 9
DAMAGETYPE_FROSTSTRIKE = 17
DAMAGETYPE_SHADOWSTRIKE = 33
DAMAGETYPE_SPELLSTRIKE = 65
DAMAGETYPE_HOLYFIRE = 6
DAMAGETYPE_HOLYSTORM = 10
DAMAGETYPE_HOLYFROST = 18
DAMAGETYPE_SHADOWLIGHT = 34
DAMAGETYPE_DIVINE = 66
DAMAGETYPE_FIRESTORM = 12
DAMAGETYPE_FROSTFIRE = 20
DAMAGETYPE_SHADOWFLAME = 36
DAMAGETYPE_SPELLFIRE = 68
DAMAGETYPE_FROSTSTORM = 24
DAMAGETYPE_SHADOWSTORM = 40
DAMAGETYPE_SPELLSTORM = 72
DAMAGETYPE_SHADOWFROST = 48
DAMAGETYPE_SPELLFROST = 80
DAMAGETYPE_SPELLSHADOW = 96
DAMAGETYPE_ELEMENTAL = 28
DAMAGETYPE_CHROMATIC = 124
DAMAGETYPE_MAGIC = 126
DAMAGETYPE_CHAOS = 127
SPELLID_AUTOSHOT = 75
(*temporary) = nil
(*temporary) = 1953
(*temporary) = "attempt to call local 'GetSkillName' (a nil value)"

1x ...ddOns/MikScrollingBattleText/MSBTAnimationStyles.lua:840: attempt to call field 'RegisterAnimationStyle' (a nil value)
[string "@MikScrollingBattleText/MSBTAnimationStyles.lua"]:840: in main chunk

Locals:
POW_FADE_IN_TIME = 0.170000
POW_DISPLAY_TIME = 1.500000
POW_FADE_OUT_TIME = 0.500000
POW_TEXT_DELTA = 0.700000
JIGGLE_DELAY_TIME = 0.050000
STATIC_DISPLAY_TIME = 3.150000
ANGLED_HORIZONTAL_PHASE_TIME = 1
ANGLED_FADE_OUT_TIME = 0.500000
ANGLED_WIDTH_PERCENT = 0.850000
MOVEMENT_SPEED = 0.011538
MIN_VERTICAL_SPACING = 8
MIN_HORIZONTAL_SPACING = 10
_ = nil
lastAngledFinishPositionY = <table> {
}
lastAngledDirection = <table> {
}
lastHorizontalPositionY = <table> {
}
lastHorizontalDirection = <table> {
}
(*temporary) = nil
(*temporary) = "Angled"
(*temporary) = "Alternate;Left;Right"
(*temporary) = "AngleUp;AngleDown"
(*temporary) = "attempt to call field 'RegisterAnimationStyle' (a nil value)"

**Comment by MetalHeadSeven** [comment]
Sorry about the wall of error text.  I put a 4 line break in between each error but it seems to have been removed.

**Comment by Hyphie24** [comment]
all good, these should already be fixed with most recent update. I'm working on cooldowns function (it's not doing the "pop" again)

**Comment by MetalHeadSeven** [comment]
Thanks so much for all you've done updating this!
