### ISSUE TITLE
error when target is in execute range

### ISSUE THREAD

**Issue by Ramza2k** [Hyphie24/MSBT-TWW#3]
Getting the following error message under very specific circumstances:

1813x ...rfaceMikScrollingBattleText/MSBTTriggers.lua:122: bad argument #1 to 'GetSpellCooldown' (Usage: local spellCooldownInfo = C_Spell.GetSpellCooldown(spellIdentifier))
[string "=[C]"]: in function `GetSpellCooldown'
[string "@MikScrollingBattleText/MSBTTriggers.lua"]:122: in function <...rfaceMikScrollingBattleText/MSBTTriggers.lua:114>
[string "@MikScrollingBattleText/MSBTTriggers.lua"]:236: in function `conditionFunc'
[string "@MikScrollingBattleText/MSBTTriggers.lua"]:605: in function <...rfaceMikScrollingBattleText/MSBTTriggers.lua:595>
[string "@MikScrollingBattleText/MSBTTriggers.lua"]:670: in function <...rfaceMikScrollingBattleText/MSBTTriggers.lua:617>
[string "@MikScrollingBattleText/MSBTTriggers.lua"]:823: in function <...rfaceMikScrollingBattleText/MSBTTriggers.lua:818>

Locals:
(*temporary) = nil

This error fires continuously if the target is in execute range while on my ret paladin, I presume because it's checking to see if hammer of wrath can be used. A similar error likely happens in all paladin specs, and any other class/spec that has an execute type skill.

**Comment by Hyphie24** [comment]
interesting, not getting it on my warrior, let me check

**Comment by Hyphie24** [comment]
on my paladin, got to execute had no errors, are you using v0.1? https://github.com/Hyphie24/MSBT-TWW/releases/tag/v0.1

**Comment by Ramza2k** [comment]
Okay, so I was, but I think I see what happened here.

I was getting that error, and I reproduced it reliably enough to try to fix it myself, though I was out of my element and couldn't. Not once during that time did I actually close the game and open it again **including when I first overwrote the version of MSBT I already had with v0.1**, I'd simply /reloaded.

When you asked me the above, I'd already closed the game, and when I opened it back up again, the error is mysteriously gone. I guess it was because I'd never closed the game and reopened it again.

**Comment by Hyphie24** [comment]
interesting, while testing /reload would always work, but so far no other error?

**Comment by Ramza2k** [comment]
I'm going to try it in an instance group because it was happening to me originally in a key, I'll report back shortly.

**Comment by Ramza2k** [comment]
It is happening in a key again

**Comment by Hyphie24** [comment]
okay so only in key, hmm

**Comment by Hyphie24** [comment]
I doubt this is why, try this, I can't seem to get it to pop, I'm in trial and error mode, in the MSBTTriggers.lua, change line 122 from 
`	local cooldownInfo = C_Spell.GetSpellCooldown(spellID);`
to
`	local cooldownInfo = C_Spell.GetSpellCooldown(skillName)`

if that doesn't work try
`	local spellCooldownInfo = GetSpellCooldown(skillName)` I'm wondering if the "spellID" is causing it or if the cooldownInfo is

**Comment by Ramza2k** [comment]
The first option fixed it

**Comment by Hyphie24** [comment]
awesome, I'll push the update
