### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by Hyphie24** [Hyphie24/MSBT-TWW#4]
*Currently bugged* 

- Cooldown "Pop" notification not showing/working, may need to alter more of the cooldownFunc - FIXED! https://github.com/Hyphie24/MSBT-TWW/commit/43a825ed249f46e030d58748d038bdac5d6c9743
- Triggers, hit edit cog next to already defined causes frame to go black & white, can't interact until /reload - fixed with https://github.com/Hyphie24/MSBT-TWW/commit/8e73a5da3465c6bc34b06c46296e133b13850b37
- beta developed hook script useitem error - fixed with https://github.com/Hyphie24/MSBT-TWW/commit/ff8d76746c47f662e9fd0f0085f2e39affe7f51d

**Comment by MetalHeadSeven** [comment]
Just a heads up these popped on the Beta Launch Test.  No issues on Live with your latest update.

1x ...faceMikScrollingBattleText/MSBTCooldowns.lua:478: hooksecurefunc(): UseItemByName is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@MikScrollingBattleText/MSBTCooldowns.lua"]:478: in main chunk

Locals:
-----------------------------------------------------------------------------------------------------------------------------------------1x ...rfaceMikScrollingBattleText/MSBTTriggers.lua:477: attempt to call field 'UpdateRegisteredEvents' (a nil value)
[string "@MikScrollingBattleText/MSBTTriggers.lua"]:477: in function `UpdateTriggers'
[string "@MikScrollingBattleText/MSBTProfiles.lua"]:3438: in function <...rfaceMikScrollingBattleText/MSBTProfiles.lua:3416>
[string "@MikScrollingBattleText/MSBTProfiles.lua"]:3555: in function <...rfaceMikScrollingBattleText/MSBTProfiles.lua:3513>
[string "@MikScrollingBattleText/MSBTProfiles.lua"]:3698: in function <...rfaceMikScrollingBattleText/MSBTProfiles.lua:3684>

Locals:
(*temporary) = nil
(*temporary) = "attempt to call field 'UpdateRegisteredEvents' (a nil value)"
eventFrame = Frame {
}
listenEvents = <table> {
}
categorizedTriggers = <table> {
}
triggerExceptions = <table> {
}
MSBTProfiles = <table> {
 masterProfile = <table> {
 }
 currentProfile = <table> {
 }
}
-----------------------------------------------------------------------------------------------------------------------------------------
1x ...faceMikScrollingBattleText/MSBTCooldowns.lua:490: hooksecurefunc(): UseItemByName is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@MikScrollingBattleText/MSBTCooldowns.lua"]:490: in main chunk

Locals:

**Comment by Hyphie24** [comment]
That seems like an easy fix, that's another that I think had the C_ change, I'll look into it soon™

Edit: if you want to test for me go into the cooldown.lua and at the top change add `local UseItemByName = C_Item.UseItemByName`
See if that may fix it

**Comment by Hyphie24** [comment]
Wrong hook script, updated on beta branch

If you don't want to edit, I'll throw up a beta repository with that change soon

**Comment by MetalHeadSeven** [comment]
Do you mean MSBTCooldowns.lua?  If so I'm using Notepad++ could you tell me where exactly to add as in line number?

**Comment by Hyphie24** [comment]
https://github.com/Hyphie24/MSBT-TWW/tree/Beta
Try this, I had wrong hook line anyways in my comment

**Comment by MetalHeadSeven** [comment]
Still getting 3 errors.  Had to copy them fast servers are shutting down.


1x ...faceMikScrollingBattleText/MSBTCooldowns.lua:490: hooksecurefunc(): UseItemByName is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@MikScrollingBattleText/MSBTCooldowns.lua"]:490: in main chunk

Locals:

1x ...rfaceMikScrollingBattleText/MSBTTriggers.lua:490: attempt to call field 'UpdateRegisteredEvents' (a nil value)
[string "@MikScrollingBattleText/MSBTTriggers.lua"]:490: in function `UpdateTriggers'
[string "@MikScrollingBattleText/MSBTProfiles.lua"]:3438: in function <...rfaceMikScrollingBattleText/MSBTProfiles.lua:3416>
[string "@MikScrollingBattleText/MSBTProfiles.lua"]:3555: in function <...rfaceMikScrollingBattleText/MSBTProfiles.lua:3513>
[string "@MikScrollingBattleText/MSBTProfiles.lua"]:3698: in function <...rfaceMikScrollingBattleText/MSBTProfiles.lua:3684>

Locals:
(*temporary) = nil
(*temporary) = "attempt to call field 'UpdateRegisteredEvents' (a nil value)"
eventFrame = Frame {
}
listenEvents = <table> {
}
categorizedTriggers = <table> {
}
triggerExceptions = <table> {
}
MSBTProfiles = <table> {
 masterProfile = <table> {
 }
 currentProfile = <table> {
 }
}

1x ...rfaceMikScrollingBattleText/MSBTProfiles.lua:3323: attempt to call field 'Enable' (a nil value)
[string "@MikScrollingBattleText/MSBTProfiles.lua"]:3323: in function <...rfaceMikScrollingBattleText/MSBTProfiles.lua:3307>
[string "@MikScrollingBattleText/MSBTProfiles.lua"]:3709: in function <...rfaceMikScrollingBattleText/MSBTProfiles.lua:3684>

Locals:
isDisabled = nil
(*temporary) = nil
(*temporary) = "attempt to call field 'Enable' (a nil value)"
savedVariables = <table> {
 profiles = <table> {
 }
}

**Comment by Hyphie24** [comment]
Okay, I'll have to look at some point. All good, thank you

**Comment by MetalHeadSeven** [comment]
You're welcome happy to do anything to help.

**Comment by Hyphie24** [comment]
Fixed, I had the wrong C_, UseItemByName uses C_Item instead of C_Container, looks like that bug is gone

I tested on retail to see if it would work, it does, so I'll post it on there and push the update after Tuesday, I feel like we'll run into that issue after Tuesday maint

**Comment by MetalHeadSeven** [comment]
Perfect zero errors now!  Let's just hope they don't do anything else before launch.

**Comment by Hyphie24** [comment]
No known issues!!!

**Comment by Arymie** [comment]
u saved my life
